  - name: copying rabbitmq repo file
    ansible.builtin.copy:
      src: rabbitmq.repo
      dest: /etc/yum.repos.d/rabbitmq.repo

  - name: Intsalling rabbitmq-server
    ansible.builtin.package:
      name: rabbitmq-server
      state: present

  - name: enabling and starting rabbitmq service
    ansible.builtin.service:
      name: rabbitmq-server
      state: started
      enabled: yes

  - name: creating rabbitmq user
    community.rabbitmq.rabbitmq_user:
      user: roboshop
      password: RABBITMQ_PASSWORD
      permissions:
        - vhost: /
          configure_priv: .*
          read_priv: .*
          write_priv: .*
      state: present